repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files

-  repo: https://github.com/frnmst/md-toc
   rev: '8.0.0'  # or a specific git tag from md-toc
   hooks:
   -    id: md-toc
        args: [-p, 'github', '-l6']  # CLI options

- repo: https://github.com/hadolint/hadolint
  rev: v2.6.0
  hooks:
  -     id: hadolint-docker
